language: node_js
node_js:
  - "stable"
notifications:
  email: false
cache:
  directories:
    - node_modules
before_script:
  - npm install
script: 
  - npm test
after_success:
  - npm run coverage
  - npm run report-coverage
  - npm run coveralls