const cars = [
  {
    id: 1,
    owner: 1,
    createdOn: new Date(),
    state: 'new',
    status: 'available',
    price: 3500000,
    manufacturer: 'Mitsubishi',
    model: 'SUV',
    bodyType: 'car',
    imageUrl: 'url',
  },
  {
    id: 2,
    owner: 2,
    createdOn: new Date(),
    state: 'used',
    status: 'sold',
    price: 1500000,
    manufacturer: 'Mack',
    model: 'Diecast',
    bodyType: 'trailer',
    imageUrl: 'url',
  },
  {
    id: 3,
    owner: 3,
    createdOn: new Date(),
    state: 'new',
    status: 'sold',
    price: 2500000,
    manufacturer: 'volkswagen',
    model: 'PickUp',
    bodyType: 'truck',
    imageUrl: 'url',
  },
  {
    id: 4,
    owner: 4,
    createdOn: new Date(),
    state: 'new',
    status: 'available',
    price: 2500000,
    manufacturer: 'Toyota',
    model: 'Sienna',
    bodyType: 'van',
    imageUrl: 'url',
  },
  {
    id: 5,
    owner: 5,
    createdOn: new Date(),
    state: 'new',
    status: 'sold',
    price: 3500000,
    manufacturer: 'Peugeot',
    model: 'PickUp',
    bodyType: 'truck',
    imageUrl: 'url',
  },
];

export default cars;
